name: docker-publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'lynx-container-tag'
        required: false
        default: ''
env:
  REGISTRY: ghcr.io
  ARM_RID: linux-arm64
  AMD_RID: linux-x64

jobs:
  publish-docker-images:
    name: Publish Docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-target: [lichess-bot-playground]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Set LICHESS-BOT-PLAYGROUND-VERSION env var
      if: env.LICHESS-BOT-PLAYGROUND-VERSION == ''
      shell: pwsh
      run: |
        echo "LICHESS-BOT-PLAYGROUND-VERSION=$("${{ github.event.inputs.tag }}".Replace('v', ''))" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Docker login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        target: ${{ matrix.docker-target }}
        platforms: |
          linux/amd64
          linux/arm64
        tags: |
          ${{ env.REGISTRY }}/lynx-chess/lichess-bot-playground:${{ env.LICHESS-BOT-PLAYGROUND-VERSION }},${{ env.REGISTRY }}/lynx-chess/lichess-bot-playground:latest
        push: true

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
