name: Create release
on:
  registry_package:
    types: [published, updated]
  workflow_dispatch:
    inputs:
      new_container_version:
        description: 'lichess-bot container release version'
        required: true
        default: ''
env:
  LICHESS_BOT_PLAYGROUND_RELEASE_TAG: ${{ github.event.registry_package.package_version.container_metadata.tag.name }}

jobs:
  create-release-bundle:
    name: Create release bundle
    if: github.event.inputs.new_container_version != '' || (github.event.registry_package.name == 'lichess-bot-playground' && github.event.registry_package.package_version.container_metadata.tag.name != 'latest' && github.event.registry_package.package_version.container_metadata.manifest.media_type == 'application/vnd.docker.distribution.manifest.list.v2+json')

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set LICHESS_BOT_PLAYGROUND_RELEASE_TAG env var
      if: env.LICHESS_BOT_PLAYGROUND_RELEASE_TAG == ''
      shell: pwsh
      run: |
        echo "LICHESS_BOT_PLAYGROUND_RELEASE_TAG=${{ github.event.inputs.new_container_version }}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Upload lichess-bot-playground v${{ env.LICHESS_BOT_PLAYGROUND_RELEASE_TAG }} artifact
      uses: actions/upload-artifact@v2
      with:
        name: lichess-bot-playground-${{ env.LICHESS_BOT_PLAYGROUND_RELEASE_TAG }}
        path: |
          Dockerfile
          README.md
          LICENSE
        if-no-files-found: error

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: lichess-bot-playground-${{ env.LICHESS_BOT_PLAYGROUND_RELEASE_TAG }}
        path: artifacts/

    - name: Compress artifact files
      run: zip -0 -r -q -j "artifacts/lichess-bot-playground-${{ env.LICHESS_BOT_PLAYGROUND_RELEASE_TAG }}.zip" "artifacts/"

    - name: Create GitHub release and upload assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        assets=()
        for asset in artifacts/*.zip; do
          assets+=("-a" "$asset")
        done
        tag_name="v${{ env.LICHESS_BOT_PLAYGROUND_RELEASE_TAG }}"
        hub release create "${assets[@]}" --draft --message "$tag_name" --message "[lichess-bot-playground $tag_name](https://github.com/lynx-chess/lichess-bot-playground/releases/tag/$tag_name)" "$tag_name"
